# Generated by Django 6.0.4 on 2026-05-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('isbn', models.CharField(max_length=60)),
                ('aviable', models.BooleanField()),
            ],
            options={
                'ordering': ['author'],
                'unique_together': {('title', 'isbn')},
            },
        ),
    ]
